# Generated by Django 5.0 on 2023-12-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=500)),
                ('variantA', models.CharField(max_length=250)),
                ('variantB', models.CharField(max_length=250)),
                ('variantC', models.CharField(max_length=250)),
                ('variantD', models.CharField(max_length=250)),
            ],
        ),
    ]
